type = "branch"
label = "Branch 4"

[position]
x = -136.01317040643693
y = -112.0300445834155

[[outgoing]]
target = "branch-2"
weight = 1

[[block]]
type = "Source"
pressure = 15.5

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"
