type = "branch"
label = "Branch 6"

[position]
x = 1212.729525447601
y = 213.8395928069079

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Sink"
