type = "branch"
label = "Branch 2"
parentId = "group-1"
diameter = "0.8 m"

[position]
x = 412.7516711069858
y = 18.285460123872497

[[outgoing]]
target = "branch-3"
weight = 1

[[outgoing]]
target = "branch-5"
weight = 3

[[block]]
type = "Pipe"

[[block]]
quantity = 2
type = "Compressor"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"
label = "special pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"
