type = "branch"
label = "Branch 7"

[position]
x = 208.5110294117647
y = 361.12132352941177

[[block]]
type = "Source"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Sink"
