type = "branch"
label = "Branch 4"

[position]
x = -290.0668025928056
y = -46.800452088620204

[[outgoing]]
target = "branch-2"
weight = 1

[[block]]
type = "Source"
pressure = 15.5
flow_rate = 3

[block.composition]
carbonDioxideFraction = 0.96
hydrogenFraction = 0.0075
nitrogenFraction = 0.0325

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"
