type = "branch"
label = "Branch 3"

[position]
x = 873.5133908398324
y = -150.83168889699513

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Sink"
