type = "branch"
label = "Branch 8"

[position]
x = 500
y = 380

[[outgoing]]
target = "branch-5"
weight = 1

[[block]]
type = "Source"
pressure = 10
flow_rate = 2

  [block.composition]
  carbonDioxideFraction = 0.9
  hydrogenFraction = 0.0675
  nitrogenFraction = 0.0325

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"
