type = "branch"
label = "Branch 3"

[position]
x = 841.9117647058824
y = -56.21323529411764

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Sink"
