type = "branch"
label = "Branch 1"
parentId = "group-1"

[position]
x = 31.473801421615534
y = 39.864923307171864

[[outgoing]]
target = "branch-2"
weight = 1

[[block]]
type = "Source"
flow_rate = 5
pressure = 10

[block.composition]
carbonDioxideFraction = 0.96
hydrogenFraction = 0.0075
nitrogenFraction = 0.0325

[[block]]
quantity = 4
type = "Capture Unit"

[[block]]
type = "Pipe"
route = "assets/spirit"

[[block]]
type = "Compressor"
pressure = "120 bar"

[[block]]
type = "Pipe"
