type = "branch"
label = "Branch 7"

[position]
x = 135.11606009887345
y = 227.7440178736691

[[block]]
type = "Source"
flow_rate = 1

[block.composition]
carbonDioxideFraction = 0.96
hydrogenFraction = 0.0075
nitrogenFraction = 0.0325

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Sink"
