type = "branch"
label = "Branch 7"

[position]
x = 300
y = 380

[[block]]
type = "Source"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Sink"
