type = "branch"
label = "Branch 1"
parentId = "group-1"

[position]
x = 71.03600530366414
y = 54.25570252486324

[[outgoing]]
target = "branch-2"
weight = 1

[[block]]
type = "Source"
pressure = 10

[[block]]
quantity = 4
type = "Capture Unit"

[[block]]
type = "Pipe"

[[block]]
type = "Compressor"
pressure = "120 bar"

[[block]]
type = "Pipe"
