type = "branch"
label = "Branch 3"

[position]
x = 763.5133908398324
y = -40.83168889699513

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Sink"
