type = "branch"
label = "Branch 1"
parentId = "group-1"

[position]
x = 28.868145219564397
y = 48.984720014350785

[[outgoing]]
target = "branch-2"
weight = 1

[[block]]
type = "Source"
pressure = 10
flow_rate = 1

  [block.composition]
  carbonDioxideFraction = 0.96
  hydrogenFraction = 0.0075
  nitrogenFraction = 0.0325

[[block]]
quantity = 4
type = "Capture Unit"

[[block]]
type = "Pipe"

[[block]]
type = "Compressor"
pressure = "120 bar"

[[block]]
type = "Pipe"
