type = "branch"
label = "Branch 8"

[position]
x = 500
y = 380

[[outgoing]]
target = "branch-5"
weight = 1

[[block]]
type = "Source"
flow_rate = 2
pressure = 10

[block.composition]
carbonDioxideFraction = 0.9
nitrogenFraction = 0.05
hydrogenFraction = 0.05

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"
