type = "branch"
label = "Branch 4"

[position]
x = -160.67267489335273
y = -128.9834539181701

[[outgoing]]
target = "branch-2"
weight = 1

[[block]]
type = "Source"
pressure = 15.5

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"
