/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShapefilesWatchRouteImport } from './routes/shapefiles/watch'
import { Route as NetworkWatchRouteImport } from './routes/network/watch'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShapefilesWatchRoute = ShapefilesWatchRouteImport.update({
  id: '/shapefiles/watch',
  path: '/shapefiles/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkWatchRoute = NetworkWatchRouteImport.update({
  id: '/network/watch',
  path: '/network/watch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/network/watch': typeof NetworkWatchRoute
  '/shapefiles/watch': typeof ShapefilesWatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/network/watch': typeof NetworkWatchRoute
  '/shapefiles/watch': typeof ShapefilesWatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/network/watch': typeof NetworkWatchRoute
  '/shapefiles/watch': typeof ShapefilesWatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/network/watch' | '/shapefiles/watch'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/network/watch' | '/shapefiles/watch'
  id: '__root__' | '/' | '/network/watch' | '/shapefiles/watch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NetworkWatchRoute: typeof NetworkWatchRoute
  ShapefilesWatchRoute: typeof ShapefilesWatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shapefiles/watch': {
      id: '/shapefiles/watch'
      path: '/shapefiles/watch'
      fullPath: '/shapefiles/watch'
      preLoaderRoute: typeof ShapefilesWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network/watch': {
      id: '/network/watch'
      path: '/network/watch'
      fullPath: '/network/watch'
      preLoaderRoute: typeof NetworkWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NetworkWatchRoute: NetworkWatchRoute,
  ShapefilesWatchRoute: ShapefilesWatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
